GET http://localhost:8080/sysproject/api/info

###
POST http://localhost:8080/sysproject/api/login
Content-Type: application/json

{
  "username": "user",
  "password": "test123"
}
###

GET http://localhost:8080/sysproject/api/info/admin
x-access-token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MTg3NzY5MiwiaWF0IjoxNjgxODc1ODkyLCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lN4PPmTtEfqarBHkCwvzBN-3fbmc_v6nLmBPp4Y0SD0

###
GET http://localhost:8080/sysproject/api/car
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MTg3NzY5MiwiaWF0IjoxNjgxODc1ODkyLCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lN4PPmTtEfqarBHkCwvzBN-3fbmc_v6nLmBPp4Y0SD0

###
POST http://localhost:8080/sysproject/api/car
Content-Type: application/json

###
GET http://localhost:8080/sysproject/api/location
x-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY4MTg3NzY5MiwiaWF0IjoxNjgxODc1ODkyLCJpc3N1ZXIiOiJzZW1lc3RlcnN0YXJ0Y29kZS1kYXQzIiwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.lN4PPmTtEfqarBHkCwvzBN-3fbmc_v6nLmBPp4Y0SD0

###
POST http://localhost:8080/sysproject/api/location
Content-Type: application/json


###
GET http://localhost:8080/sysproject/api/info/create
Content-Type: application/json

{
  "username": "",
  "password": ""
}
